linux: refactor init

diff --git a/linux/packages/init/init b/linux/packages/init/init
--- a/linux/packages/init/init
+++ b/linux/packages/init/init
@@ -1,33 +1,7 @@
 #!/bin/busybox sh
 
-# First, install symbolic links to /busybox into /bin and /sbin.
-/bin/busybox mkdir -p /sbin /bin
-/bin/busybox --install -s
-
-
-cd /
-mkdir -p sys proc tmp app
-mount -t sysfs    sysfs    /sys
-mount -t securityfs securityfs /sys/kernel/security
-mount -t proc     proc     /proc
-mount -t devtmpfs devtmpfs /dev
-
-cat <<"EOF"
- __  __       _        ____  _             _       _     _
-|  \/  | __ _| | _____/ ___|| |_ __ _  ___| | __  | |   (_)_ __  _   ___  __
-| |\/| |/ _` | |/ / _ \___ \| __/ _` |/ __| |/ /  | |   | | '_ \| | | \ \/ /
-| |  | | (_| |   <  __/___) | || (_| | (__|   <   | |___| | | | | |_| |>  <
-|_|  |_|\__,_|_|\_\___|____/ \__\__,_|\___|_|\_\  |_____|_|_| |_|\__,_/_/\_\
-
-EOF
-
-root=$(egrep -o "root=([^ ]+)" /proc/cmdline | awk -F= '{print $2}')
-[ "$root" = "" ] || echo "Error: root is not speicifed in /proc/cmdline" > /dev/stderr
-mkdir /boot
-mount $root /boot
-
-. /boot/config.sh
-hostname makestack-linux
+RANDSEED_FILE=/boot/randseed
+RANDSEED_SIZE=512
 
 start_daemon() {
   script=$1
@@ -46,47 +20,112 @@ start_daemon() {
   done
 }
 
-if [ "$DISABLE_APPARMOR" = "yes" ]; then
-  apparmor_parser -C -r /etc/apparmor.d/*
-else
-  apparmor_parser -r /etc/apparmor.d/*
-fi
+init_busybox() {
+  # Install symbolic links to /busybox into /bin and /sbin.
+  /bin/busybox mkdir -p /sbin /bin
+  /bin/busybox --install -s
+}
 
-# Initialize random seed.
-RANDSEED_FILE=/boot/randseed
-RANDSEED_SIZE=512
-if [ -f "$RANDSEED_FILE" ]; then
-  echo "*** Feeding random seed"
-  cat "$RANDSEED_FILE" > /dev/urandom
-fi
+mount_filesystems() {
+  mkdir -p sys proc tmp app dev
+  mount -t sysfs    sysfs    /sys
+  mount -t securityfs securityfs /sys/kernel/security
+  mount -t proc     proc     /proc
+  mount -t devtmpfs devtmpfs /dev
+  mknod /dev/console c 5 1
 
-if [ "$MAKESTACK_NETWORK_ADAPTER" = "http" ]; then
-  for interface in $(echo /sys/class/net/* | xargs -n1 basename); do
-    [ "$interface" = "lo" ] && continue
-    [ "$interface" = "irlan0" ] && continue
+  # Redirect stdout and stderr to the console.
+  exec > /dev/console 2>&1
 
-    echo "*** Initializing $interface"
-    ip link set $interface up
-    start_daemon "udhcpc -f -i $interface -s /etc/udhcpc.script" &
-  done
-fi
+  root=$(egrep -o "root=([^ ]+)" /proc/cmdline | awk -F= '{print $2}')
+  [ "$root" = "" ] || echo "Error: root is not speicifed in /proc/cmdline" > /dev/stderr
+  mkdir /boot
+  mount $root /boot
+}
 
-if [ "$MAKESTACK_NETWORK_ADAPTER" = "http" ]; then
-  start_daemon "ntpd -n -p 1.pool.ntp.org" &
-fi
+banner() {
+  cat <<"EOF"
+ __  __       _        ____  _             _       _     _
+|  \/  | __ _| | _____/ ___|| |_ __ _  ___| | __  | |   (_)_ __  _   ___  __
+| |\/| |/ _` | |/ / _ \___ \| __/ _` |/ __| |/ /  | |   | | '_ \| | | \ \/ /
+| |  | | (_| |   <  __/___) | || (_| | (__|   <   | |___| | | | | |_| |>  <
+|_|  |_|\__,_|_|\_\___|____/ \__\__,_|\___|_|\_\  |_____|_|_| |_|\__,_/_/\_\
 
-echo "*** Boot time: $(awk '{print $1}' /proc/uptime) secs"
+EOF
+}
 
-export MAKESTACK_APP_UID=0
-export MAKESTACK_APP_GID=0
-echo "*** Starting MakeStack Supervisor..."
+load_config_sh() {
+  . /boot/config.sh
+}
 
-# Don't append `&'. start_daemon must return if the supervisor exited with 0 to reboot.`
-start_daemon "node /supervisor/supervisor"
+set_hostname() {
+  hostname makestack-linux
+}
 
-echo "*** Saving random seed..."
-dd if=/dev/urandom of=$RANDSEED_FILE bs=$RANDSEED_SIZE count=1
+init_apparmor() {
+  if [ "$DISABLE_APPARMOR" = "yes" ]; then
+    apparmor_parser -C -r /etc/apparmor.d/*
+  else
+    apparmor_parser -r /etc/apparmor.d/*
+  fi
+}
 
-echo "*** Rebooting in 10 seconds..."
-sleep 10
-reboot -f
+init_urandom() {
+  if [ -f "$RANDSEED_FILE" ]; then
+    echo "*** Feeding random seed"
+    cat "$RANDSEED_FILE" > /dev/urandom
+  fi
+}
+
+init_networking() {
+  if [ "$MAKESTACK_NETWORK_ADAPTER" = "http" ]; then
+    for interface in $(echo /sys/class/net/* | xargs -n1 basename); do
+      [ "$interface" = "lo" ] && continue
+      [ "$interface" = "irlan0" ] && continue
+
+      echo "*** Initializing $interface"
+      ip link set $interface up
+      start_daemon "udhcpc -f -i $interface -s /etc/udhcpc.script" &
+    done
+
+    start_daemon "ntpd -n -p 1.pool.ntp.org" &
+  fi
+}
+
+start_supervisor() {
+  export MAKESTACK_APP_UID=0
+  export MAKESTACK_APP_GID=0
+  echo "*** Starting MakeStack Supervisor..."
+
+  # Don't append `&'. `start_daemon`` must return if the supervisor exited with 0 to reboot.
+  start_daemon "node /supervisor/supervisor"
+}
+
+save_urandom_seed() {
+  echo "*** Saving random seed..."
+  dd if=/dev/urandom of=$RANDSEED_FILE bs=$RANDSEED_SIZE count=1
+}
+
+init() {
+  cd /
+
+  init_busybox
+  mount_filesystems
+  banner
+  load_config_sh
+  set_hostname
+  init_apparmor
+  init_urandom
+  init_networking
+
+  echo "*** Boot time: $(awk '{print $1}' /proc/uptime) secs"
+  start_supervisor
+
+  # Supervisor exited with 0. Do some work and reboot.
+  save_urandom_seed
+  echo "*** Rebooting in 10 seconds..."
+  sleep 10
+  reboot -f
+}
+
+init
