linux: initialize /dev/console before mounting the root file system

diff --git a/linux/packages/init/init b/linux/packages/init/init
--- a/linux/packages/init/init
+++ b/linux/packages/init/init
@@ -34,13 +34,18 @@ mount_filesystems() {
   mount -t devtmpfs devtmpfs /dev
   mknod /dev/console c 5 1
 
+  # Redirect stdout and stderr to the console.
+  exec > /dev/console 2>&1
+
   root=$(egrep -o "root=([^ ]+)" /proc/cmdline | awk -F= '{print $2}')
-  [ "$root" = "" ] || echo "Error: root is not speicifed in /proc/cmdline" > /dev/stderr
+  if [ "$root" = "" ]; then
+    echo "Error: root is not speicifed in /proc/cmdline"
+    exit 1
+  fi
+
   mkdir /boot
   mount $root /boot
 
-  # Redirect stdout and stderr to the console.
-  exec > /dev/console 2>&1
   dmesg > /boot/boot.log
 }
 
